// This file is generated by `pnpm run generate:data`. Do not edit by hand.
export const pluginsGeneratedAt = "2026-04-08T21:55:40.881Z";

export const plugins = [
  {
    "slug": "slides.nvim",
    "name": "slides.nvim",
    "description": "Neovim plugin for presenting Markdown slides in a full-screen floating window.",
    "repository": "matt-riley/slides.nvim",
    "homepage": "https://github.com/matt-riley/slides.nvim",
    "version": "v0.1.4",
    "updatedAt": "2026-04-03T08:46:45Z",
    "language": "Lua",
    "topics": [
      "lua",
      "markdown",
      "neovim",
      "neovim-plugin",
      "presentations"
    ],
    "lazyInstallSnippet": "{ \"matt-riley/slides.nvim\" }",
    "vimPackInstallSnippet": "vim.pack.add({ 'https://github.com/matt-riley/slides.nvim' })"
  },
  {
    "slug": "waystone.nvim",
    "name": "waystone.nvim",
    "description": "Neovim plugin for persistent project marks with scoped slots and quick jumping.",
    "repository": "matt-riley/waystone.nvim",
    "homepage": "https://github.com/matt-riley/waystone.nvim",
    "version": "v0.1.3",
    "updatedAt": "2026-04-03T09:59:55Z",
    "language": "Lua",
    "topics": [
      "lua",
      "navigation",
      "neovim",
      "neovim-plugin",
      "productivity"
    ],
    "lazyInstallSnippet": "{ \"matt-riley/waystone.nvim\" }",
    "vimPackInstallSnippet": "vim.pack.add({ 'https://github.com/matt-riley/waystone.nvim' })"
  }
] as const;
