// This file is generated by `pnpm run generate:data`. Do not edit by hand.
export const generatedAt = "2026-04-08T06:37:26.293Z";

export const tools = [
  {
    "slug": "hopt",
    "name": "hopt",
    "description": "A TUI to interact with The Hoptimist store",
    "homepage": "https://github.com/matt-riley/hopcli",
    "version": "0.2.2",
    "license": null,
    "installCommand": "brew install matt-riley/tools/hopt",
    "binaryNames": [
      "hopt"
    ],
    "platforms": [
      "macOS (Intel, Apple Silicon)",
      "Linux (x86_64, arm64)"
    ],
    "formulaFile": "Formula/hopt.rb"
  },
  {
    "slug": "newbrew",
    "name": "newbrew",
    "description": "Browse and inspect new Homebrew formulae from your terminal",
    "homepage": "https://github.com/matt-riley/newbrew",
    "version": "0.1.2",
    "license": null,
    "installCommand": "brew install matt-riley/tools/newbrew",
    "binaryNames": [
      "newbrew"
    ],
    "platforms": [
      "macOS (Intel, Apple Silicon)",
      "Linux (x86_64, arm64)"
    ],
    "formulaFile": "Formula/newbrew.rb"
  },
  {
    "slug": "tui",
    "name": "tui",
    "description": "Workv2 terminal UI",
    "homepage": "https://github.com/matt-riley/workv2",
    "version": "0.4.2",
    "license": "MIT",
    "installCommand": "brew install matt-riley/tools/tui",
    "binaryNames": [
      "mattriley"
    ],
    "platforms": [
      "macOS (Intel, Apple Silicon)",
      "Linux (x86_64, arm64)"
    ],
    "formulaFile": "Formula/tui.rb"
  }
] as const;
