name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: matt-riley/matt-riley-ci/.github/workflows/node-ci.yml@bd605dc142b75bef90c69f2707997f8cb161abc8 # main
    with:
      package-manager: pnpm
      run-lint: true
      run-test: true
      run-build: true

  deploy:
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: matt-riley/matt-riley-ci/.github/workflows/request-infra-deploy.yml@924fe06ffe4b4bd8637220bd5a950d56b4ed41a0
    with:
      app-name: mattriley-tools
    secrets:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
