name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: matt-riley/matt-riley-ci/.github/workflows/node-ci.yml@556c658a6a3ce52b1f7e219e30eb70dcd2fe4f31 # main
    with:
      package-manager: pnpm
      run-lint: true
      run-test: true
      run-build: true

  deploy:
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/request-infra-deploy.yml
    with:
      app-name: mattriley-tools
    secrets:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
